---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: growing_startup
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: growing_startup   #your name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: growing_startup   #your name
  tags:
    karpenter.sh/discovery: growing_startup       #your name
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"] #"spot"
        - key: "node.kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"] #diversify arch
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.nano", "t3.micro", "t2.medium", "t3.medium", "t3a.medium"]
  limits:
    cpu: 20
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s